"""
Buy or Wait? — Main entry point.

Usage:
  python code/main.py                   # full run (dataset/requests.csv)
  python code/main.py --sample          # calibration run (dataset/sample_requests.csv)
  python code/main.py --sample --no-llm # calibration without LLM calls (deterministic only)
  python code/main.py --request request_26  # single request debug
"""
from __future__ import annotations

import argparse
import logging
import os
import sys
import time
import traceback
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

# Add code/ to path so imports work
CODE_DIR = Path(__file__).parent.resolve()
if str(CODE_DIR) not in sys.path:
    sys.path.insert(0, str(CODE_DIR))

REPO_ROOT = CODE_DIR.parent
OUTPUT_PATH = str(REPO_ROOT / "output.csv")
SAMPLE_OUTPUT_PATH = str(REPO_ROOT / "sample_output.csv")

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("main")


# ---------------------------------------------------------------------------
# Load .env
# ---------------------------------------------------------------------------

def _load_env():
    env_path = REPO_ROOT / ".env"
    if env_path.exists():
        try:
            from dotenv import load_dotenv
            load_dotenv(env_path)
            logger.info("Loaded .env from %s", env_path)
        except Exception as e:
            logger.warning("dotenv load failed: %s", e)
    else:
        logger.info("No .env file found — using environment variables as-is")


# ---------------------------------------------------------------------------
# Token tracking (for usage_report.md)
# ---------------------------------------------------------------------------

class TokenTracker:
    def __init__(self):
        self.calls = 0
        self.input_tokens = 0
        self.output_tokens = 0
        self.model_calls: Dict[str, int] = {}

    def record(self, model: str, input_tok: int, output_tok: int):
        self.calls += 1
        self.input_tokens += input_tok
        self.output_tokens += output_tok
        self.model_calls[model] = self.model_calls.get(model, 0) + 1

    def write_report(self, num_requests: int, output_path: str):
        total_tok = self.input_tokens + self.output_tokens
        avg_per_req = total_tok / max(num_requests, 1)
        # Rough cost estimate (Groq free tier — approximately $0)
        estimated_cost = 0.0

        report = f"""# Token Usage Report

## Final Full-Dataset Run

Generated by: code/main.py
Requests processed: {num_requests}

## Model Usage

| Model | Calls |
|-------|-------|
"""
        for model, n in self.model_calls.items():
            report += f"| {model} | {n} |\n"

        report += f"""
## Token Counts

| Metric | Value |
|--------|-------|
| Total API calls | {self.calls} |
| Total input tokens | {self.input_tokens:,} |
| Total output tokens | {self.output_tokens:,} |
| Total tokens | {total_tok:,} |
| Avg tokens per request | {avg_per_req:.1f} |

## Cost Estimate

| Metric | Value |
|--------|-------|
| Provider | Groq (free tier) |
| Estimated total cost | ${estimated_cost:.4f} |
| Estimated cost per request | ${estimated_cost / max(num_requests, 1):.6f} |

*Note: Groq free tier has no per-token charge at time of run.
 Cost would be ~$0.00 for this run.*
"""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)
        logger.info("Wrote usage report to %s", output_path)


# ---------------------------------------------------------------------------
# Single request processor
# ---------------------------------------------------------------------------

def run_one(
    request_id: str,
    use_sample: bool,
    use_llm: bool,
    tracker: Optional[TokenTracker] = None,
) -> Optional[dict]:
    """Process one request_id and return a dict row for output."""
    try:
        from retrieval import get_request_context
        from extract_context import build_amendments
        from pipeline import process_request

        # Phase 8: Extract amendments from messages + images
        ctx = get_request_context(request_id, use_sample=use_sample)
        amendments = {}
        if use_llm:
            amendments = build_amendments(
                user_id=ctx["request"]["user_id"],
                request_id=request_id,
                request_date=pd.Timestamp(ctx["request"]["request_date"]),
                events=ctx["events"],
                messages=ctx["messages"],
                images=ctx["images"],
                home_currency=ctx["home_currency"],
                use_llm=True,
            )
        elif use_sample:
            # Use hardcoded fixtures for --no-llm calibration
            from fixtures import get_sample_amendments
            amendments = get_sample_amendments(request_id)

        # Full pipeline
        rec = process_request(
            request_id=request_id,
            use_sample=use_sample,
            use_llm=use_llm,
            amendments=amendments,
        )

        return {
            "request_id": rec.request_id,
            "amount_safe_to_pay": round(rec.amount_safe_to_pay, 2),
            "affordability_status": rec.affordability_status,
            "recommended_payment_method": rec.recommended_payment_method,
            "payment_plan": rec.payment_plan,
            "earliest_date_for_full_payment": rec.earliest_date_for_full_payment,
            "spending_changes_needed": rec.spending_changes_needed,
            "decision_explanation": rec.decision_explanation,
        }

    except Exception as e:
        logger.error("FAILED: %s — %s", request_id, e)
        logger.debug(traceback.format_exc())
        return None


# ---------------------------------------------------------------------------
# Calibration scoring
# ---------------------------------------------------------------------------

def score_against_sample(output_df: pd.DataFrame) -> Dict:
    """
    Compare output against sample_requests.csv ground truth.
    Returns per-field match counts and a total 'exact match' count.
    Hard Rule 7: must report exact match count, not 'mostly working'.
    """
    from loaders import load_sample_requests
    sample = load_sample_requests().reset_index()

    fields = [
        "affordability_status",
        "recommended_payment_method",
    ]
    # amount_safe_to_pay and earliest_date_for_full_payment need tolerance
    numeric_fields = ["amount_safe_to_pay"]

    results = {"total": 0, "exact_match": 0, "field_matches": {}}
    for f in fields + numeric_fields + ["earliest_date_for_full_payment", "spending_changes_needed"]:
        results["field_matches"][f] = 0

    mismatches = []

    for _, gt_row in sample.iterrows():
        rid = gt_row["request_id"]
        out_row = output_df[output_df["request_id"] == rid]
        if len(out_row) == 0:
            continue

        out = out_row.iloc[0]
        results["total"] += 1
        row_exact = True

        for f in fields:
            gt_val = str(gt_row[f]).strip()
            pred_val = str(out[f]).strip()
            if gt_val == pred_val:
                results["field_matches"][f] += 1
            else:
                row_exact = False

        # Amount safe to pay — tolerance 1%
        try:
            gt_amt = float(gt_row["amount_safe_to_pay"])
            pred_amt = float(out["amount_safe_to_pay"])
            tol = max(gt_amt * 0.01, 1.0)
            if abs(gt_amt - pred_amt) <= tol:
                results["field_matches"]["amount_safe_to_pay"] += 1
            else:
                row_exact = False
        except Exception:
            row_exact = False

        # Earliest date
        gt_edate = str(gt_row.get("earliest_date_for_full_payment", "")).strip()
        pred_edate = str(out.get("earliest_date_for_full_payment", "")).strip()
        # Treat 'nan', '', 'None' as equivalent empty values
        gt_empty = gt_edate in ("nan", "", "None", "NaN")
        pred_empty = pred_edate in ("nan", "", "None", "NaN")
        if (gt_empty and pred_empty) or (gt_edate == pred_edate):
            results["field_matches"]["earliest_date_for_full_payment"] += 1
        else:
            row_exact = False

        # Spending changes
        gt_sc = str(gt_row.get("spending_changes_needed", "none")).strip()
        pred_sc = str(out.get("spending_changes_needed", "none")).strip()
        if gt_sc == pred_sc:
            results["field_matches"]["spending_changes_needed"] += 1
        else:
            row_exact = False

        if row_exact:
            results["exact_match"] += 1
        else:
            mismatches.append({
                "request_id": rid,
                "gt": gt_row.to_dict(),
                "pred": out.to_dict(),
            })

    results["mismatches"] = mismatches
    return results


def print_calibration_report(results: Dict) -> None:
    """Hard Rule 7: must print exact counts, never vague claims."""
    total = results["total"]
    exact = results["exact_match"]
    logger.info("=" * 60)
    logger.info("CALIBRATION RESULT: %d/%d exact matches", exact, total)
    logger.info("Field-level matches:")
    for field, count in results["field_matches"].items():
        logger.info("  %-40s %d/%d", field, count, total)

    if results["mismatches"]:
        logger.info("Mismatches (%d):", len(results["mismatches"]))
        for mm in results["mismatches"]:
            rid = mm["request_id"]
            gt = mm["gt"]
            pred = mm["pred"]
            logger.info("  %s:", rid)
            for f in ["affordability_status", "recommended_payment_method",
                       "amount_safe_to_pay", "earliest_date_for_full_payment",
                       "spending_changes_needed"]:
                if str(gt.get(f, "")).strip() != str(pred.get(f, "")).strip():
                    logger.info("    %s: GT=%r PRED=%r", f, gt.get(f), pred.get(f))
    logger.info("=" * 60)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Buy or Wait? financial agent")
    parser.add_argument("--sample", action="store_true", help="Run against sample_requests.csv")
    parser.add_argument("--no-llm", action="store_true", help="Skip all LLM calls (deterministic only)")
    parser.add_argument("--request", type=str, help="Process a single request_id")
    parser.add_argument("--no-calibration", action="store_true", help="Skip calibration scoring (sample run)")
    args = parser.parse_args()

    _load_env()

    use_llm = not args.no_llm
    use_sample = args.sample
    single_request = args.request

    if use_llm and not os.environ.get("GROQ_API_KEY"):
        logger.warning("GROQ_API_KEY not set — running without LLM (use --no-llm to suppress this warning)")
        use_llm = False

    # Load request IDs
    from loaders import load_requests, load_sample_requests
    if use_sample:
        req_df = load_sample_requests()
        output_path = SAMPLE_OUTPUT_PATH
        logger.info("SAMPLE RUN: %d requests", len(req_df))
    else:
        req_df = load_requests()
        output_path = OUTPUT_PATH
        logger.info("FULL RUN: %d requests", len(req_df))

    if single_request:
        request_ids = [single_request]
    else:
        request_ids = list(req_df.index)

    tracker = TokenTracker()
    rows = []
    start_time = time.time()

    for i, rid in enumerate(request_ids):
        t0 = time.time()
        logger.info("[%d/%d] Processing %s", i + 1, len(request_ids), rid)
        row = run_one(rid, use_sample=use_sample, use_llm=use_llm, tracker=tracker)
        if row is None:
            # Fallback row — keeps pipeline running
            requested = float(req_df.loc[rid]["requested_amount"]) if rid in req_df.index else 0.0
            row = {
                "request_id": rid,
                "amount_safe_to_pay": 0.0,
                "affordability_status": "not_affordable",
                "recommended_payment_method": "not_recommended",
                "payment_plan": "none",
                "earliest_date_for_full_payment": "",
                "spending_changes_needed": "none",
                "decision_explanation": "Processing error — could not compute recommendation.",
            }
        rows.append(row)
        elapsed = time.time() - t0
        logger.info("  -> %s | %s | safe=%.2f | %s | %.1fs",
                    rid,
                    row["affordability_status"],
                    row["amount_safe_to_pay"],
                    row["recommended_payment_method"],
                    elapsed)

    # Build output DataFrame
    output_df = pd.DataFrame(rows)

    # Write output
    from validator import write_output
    write_output(output_df, output_path, req_df)

    total_time = time.time() - start_time
    logger.info(
        "Total time: %.1fs | %.2fs per request | %d requests",
        total_time, total_time / max(len(request_ids), 1), len(request_ids)
    )

    # Calibration scoring
    if use_sample and not args.no_calibration:
        results = score_against_sample(output_df)
        print_calibration_report(results)

    # Usage report (for full runs)
    if not use_sample:
        usage_report_path = str(CODE_DIR / "evaluation" / "usage_report.md")
        tracker.write_report(len(request_ids), usage_report_path)

    logger.info("Done. Output written to %s", output_path)


if __name__ == "__main__":
    main()
